name: TestPlugin
main: com.alphaae.mcpe.servers.TestPlugin
version:  "1.0.0"
api: ["1.0.8"]

load: POSTWORLD

author: alphaAE
description: AlpheAE的测试插件
website: http://www.alphaae.com

permissions:
  testplugin.command.hi:
    description: 允许用户使用hi指令
    default: true
  testplugin.command.menu:
    description: 允许用户使用menu指令
    default: true

commands:
  hi:
    description: hi指令
    usage: "/hi"
    permission: testplugin.command.hi
#  menu:
#    description: 菜单指令
#    usage: "/menu"
#    permission: testplugin.command.hi