name: MainPlugin
main: com.alphaae.mcpe.servers.MainPlugin
version:  "1.0.0"
api: ["1.0.8"]

load: POSTWORLD

author: alphaAE
description: AlpheAE的测试插件
website: http://www.alphaae.com

permissions:
  testplugin.command.menu:
    description: 允许用户使用menu指令
    default: true

#commands:
#  hi:
#    description: 测试指令
#    usage: "/hi"
#    permission: testplugin.command.menu