name: AlphaAPI
main: com.alphaae.mcpe.servers.MainPlugin
version:  "1.0.0"
api: ["1.0.8"]

load: POSTWORLD

author: alphaAE
description: AlpheAE 插件组 核心插件
website: http://www.alphaae.com

permissions:
  alphaapi.command.console:
    description: 允许控制台使用的指令
    default: false
  alphaapi.command.op:
    description: 允许OP用户使用的指令
    default: op
  alphaapi.command.everybody:
    description: 允许所有用户使用的指令
    default: true

#commands:
#  hi:
#    description: 测试指令
#    usage: "/hi"
#    permission: testplugin.command.menu